# This credentials secret allows cloudflared to authenticate itself
# to the Cloudflare infrastructure.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-tunnel.fullname" . }}
  labels:
    {{- include "cloudflare-tunnel.labels" . | nindent 4 }}
stringData:
  credentials.json: |-
    {
      "AccountTag": {{ .Values.secrets.cloudflare.account | quote }},
      "TunnelID": {{ .Values.secrets.cloudflare.tunnelId | quote }},
      "TunnelSecret": {{ .Values.secrets.cloudflare.secret | quote }}
    }
