apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quiz-frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quiz-frontend.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "quiz-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "quiz-frontend.selectorLabels" . | nindent 8 }}

    spec:
      serviceAccountName: {{ include "quiz-frontend.serviceAccountName" . }}

      containers:
        - name: quiz-frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP


          # probes
          {{- if .Values.probes.enabled }}

          livenessProbe:
            {{- toYaml .Values.probes.liveness | nindent 12 }}

          readinessProbe:
            {{- toYaml .Values.probes.readiness | nindent 12 }}

          {{- end }}

          # requests and limits
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
