# allows the HTTPRoute in the platform namespace
# to forward traffic to this service
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-platform-routing
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quiz-frontend.labels" . | nindent 4 }}
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: platform
  to:
    - group: ""
      kind: Service
