{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quiz-frontend.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quiz-frontend.labels" . | nindent 4 }}
{{- end }}
