apiVersion: v1
kind: Secret
metadata:
  name: quiz-multiplayer-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quiz-multiplayer.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  INTERNAL_SERVICE_SECRET: {{ .Values.secrets.internalServiceSecret | quote }}
