apiVersion: v1
kind: Service
metadata:
  name: {{ include "quiz-multiplayer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quiz-multiplayer.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  sessionAffinity: ClientIP  # Sticky sessions for WebSocket
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "quiz-multiplayer.selectorLabels" . | nindent 4 }}
