apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass 
metadata:
  name: {{ .Values.gateway.className }}
  # no namespace, cluster scoped resource
  labels:
    {{- include "quiz-platform.labels" . | nindent 4 }}
spec:
  controllerName: {{ .Values.gateway.controllerName }}
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: {{ .Values.gateway.proxyName }}
    namespace: envoy-gateway-system