#ENC[AES256_GCM,data:xcYqX/KMlRoqOjNEfyq6a+ka45aBDbc+bHTF0mveXZSTf7fg3EeiGhIQJMh6ZiOGBvt52VRlqHHKhbRkgpO1,iv:CANsXaHbpQ+sR+gY99deoV7AU1DuD1G3zvHB2BayQrw=,tag:gVslw0u3P7MuTYvjRhZdRQ==,type:comment]
#ENC[AES256_GCM,data:WsH6W1b/gX5+GJzBmZsQdPPbAtKAtUE9uAiQqY5ZJhc3VJ7Vewvpnmjvzu3JWjOD0e3EkZ11Gke7VpEb/Rw=,iv:DsA5v6xq7NG4fTdfGLJI60Q2kTe6EVS9EMQ+PREu1e0=,tag:0B64bqisMcgpGabTkjGfsw==,type:comment]
#ENC[AES256_GCM,data:Dr2s+wBG1VOkc1B1LZWzDG8gTovvgpiXWjlILT6AB+i1Gj5sj5r4xg==,iv:SDCHKlk2q1m/htkzVPIrEoHz9QRDeLbPsJmhC7vOi44=,tag:9QdLksd/51+chEEcwhEpaA==,type:comment]
secrets:
    #ENC[AES256_GCM,data:xKprVgNg1apMYmudPVkFNhFJuDn1v6MWl/g5nSvsIZo7wUjvViKJ+q9y2OKeNw==,iv:43i5CSetZAtNj4I25rXI/IYSn9lKi0Pj5hIz94SFrkw=,tag:i6UcY6KCUVOI18v0hhyUdg==,type:comment]
    openaiApiKey: ""
    mongodbPassword: ENC[AES256_GCM,data:SrzxuaR1gp6zu4dAu9SJJMon6AbAxvEauLuODb5E4hx1f+DmooIIAFkaUmINpW8r,iv:+wsWe79Gl/GLhOxb0U4HvW8u8pdKX3Y0arNdlROY8ls=,tag:fKi/b6hV5jvIRmpgnQxemA==,type:str]
    internalServiceSecret: ENC[AES256_GCM,data:pBBC8rrJsiMRB6nElVcx4Qakc0UsY3Awfo9MJyI875HWsQbHXwfMVN5mAbk=,iv:1hFBhpW2XjSAfNbmKgpYBPozCmCdfP27e5l6ouF90hs=,tag:faaUNAqToV2Joqa45J/8eA==,type:str]
    googleClientId: ENC[AES256_GCM,data:80hXcVyKjXIgg3mnKNtcDRxfjHlgQMyr81hti+VCNQlhCc/85Dsl6NbyzYQ0MeRDR6oMpd/uXQwz+Cj7QnWXo/8aHvP4VXhz,iv:XpSmUKvJuy6Ba5d95ObWEWyO6OO/VLluXSvNvUG4C2U=,tag:tCTCZ6eeNIwTZeMvTWYF1A==,type:str]
    googleClientSecret: ENC[AES256_GCM,data:4j4Et6FZoKL25pGTeZ8Bd5NNDjcJllHBk3kVzxXvJoAZ5i0=,iv:SEo9dCNacERJWkIQuWI0/FxAZvdMM/7EVL1bvyZqDWg=,tag:6a1sHk6x2vyzK1NIrA3d9w==,type:str]
    jwtSecret: ENC[AES256_GCM,data:S3xBE/632TyOOmKUa+Q9gE2Rg6jjAxO2FNbDvaf38g8iX1XDJJ0XHXT6g/o=,iv:RuPlGt4tGj9V2uY0db4F2ji4U+SIdTJqcWv9UuQXqaY=,tag:qx3xw0dPbAzw0iB1c9NFew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12t2lrvjt7r8k7sx2ef0q5wc9xj8kk3upxzr0kx3mqgya557z0uxsvna00u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UndMdkVmd3hUV3dBdVpj
            a1I1UlBhVXBCZnJheUdLcnNLVXFLVE05cjBVCnNSVlFWTE5acXNreUpGNytWUjB6
            KzFVY2dDZ2xaMGdpN3BqMGxsWlAxeFkKLS0tIHN4L3Q4VHZHajlrSW9WREZ2bGUv
            YjUzZm5ITCtNUzZTZGtzMXAvK1JmaFEKJYEs/NXjBKEGh/7Gi8X9QCtpSnWX0HxT
            E/SI0zMfRzRXEKu7Oxc1cndyDQnA/SP9MqKbF+/ALVFBIfDytBPsdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T23:57:18Z"
    mac: ENC[AES256_GCM,data:rcxt6tatExOogjG17ycMonvkMsQYouM7MhfHGDWbhg+A351CdQpYfGW2u+nSMrkzls62kVQBHLO9/rYe+d0WunORbcoipO8GJWQrxSRFwB60ob21uvmfvcqimWBGEHArIB/xmUWqu8tk7hxLHePq8WhbBaN/Gj59oDgeqopWv3g=,iv:yUxVASQ4aMiV/eumr/G/1a2IG05u8Flg0nYz4CASuWI=,tag:Bl9w3WBhdEMRDWA0pk17TQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
