# to be implemented
# encrypt this file with: sops --encrypt --in-place secrets.yaml
# or create it encrypted from the start with: sops secrets.yaml
secrets:
  jwtSecret: ""             # to be implemented (must match quiz-backend)
  internalServiceSecret: "" # to be implemented (must match quiz-backend)
