#ENC[AES256_GCM,data:1cj0QouU0wQWotUhY/Y8lgp/p+q81P/7+ZA1Ey116WwYHICDwFXcOC3gXO7UhDJZ4GpygKWYAz5nl8pyiMr0,iv:4faKmI3XoTXVCJV05lm7/VVFfXNjaiIXnhsF2YwMHC0=,tag:Nethet1gUeLAvI4nK03ifg==,type:comment]
#ENC[AES256_GCM,data:py+ssEvMOntbuj77DkZaSX8RUHieXEBhSVarIT7HiskTwP1Mq4e7Xb0CzomQOAmRJB/M9M43STUl86KmE+U=,iv:94+u/6bYUvqvsVnT7d0FvwitAlWSjJyJDVMisjyYR5E=,tag:R/jLNtb8Tjy5HYZhnxw0Lw==,type:comment]
#ENC[AES256_GCM,data:KibZ1YD18CfmNxVpFqb8wVK7p/5QHmiBpZRwGBjra3rlVtxgs50AWQ==,iv:4x6Gqej5Z/eehdn2dc1KLN9l4yPcWHIgNZjvjcbC8vo=,tag:bgONnnN2A7A1PJe8vwx+zQ==,type:comment]
secrets:
    jwtSecret: ENC[AES256_GCM,data:WfcnijZ2OGoQzNJ3hLRH6iLbhQuVNeepWYJNEItY5YmmUad+rfgiJNm/xg4=,iv:NifkP5MKZVZCnkteqt06XB2KsepDBvxqmUZFGvumbpo=,tag:M6QPqXA4YjgnQVC2ER/HPA==,type:str]
    internalServiceSecret: ENC[AES256_GCM,data:khOLyuRfSOkb8wvOPTWwFFqGB3OP3bFIu7xU5ntjgNU41KD1XGmXEe+d5JI=,iv:J8p3NdndhfOaoE6yxkOY1B7hJoxQLIFFm0jJFKlx/E4=,tag:uxwBdaqsSjryiuEVbV/9hA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12t2lrvjt7r8k7sx2ef0q5wc9xj8kk3upxzr0kx3mqgya557z0uxsvna00u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNytKVXEra3l0YWltSXV1
            eDkzZWZGS3B5a3pxRkFEZGZWSWpzb3I2REQ0CkdzcWc2eGxwTkRPZDhFSG5KVlF2
            M0gyNWkyOXo2U3Ruc3MzdzdjdmFzUmsKLS0tIHdZSjMvRWd3ZzkvUnVQelQ2cXJa
            QU5vL1ZqcVhNcWtFOG5mUzhHS0JyUjgKcVZ+O/5q6xE0fCe5otmBmemkiPtjUetF
            mN+xU8tnYlAs0tslnSXtFNTzcVFhZ2etyu9Dn7p7Q5zGmlJ0rxU9Eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T17:59:25Z"
    mac: ENC[AES256_GCM,data:No8puGdXEWXCkCNCdDeMFQS9pIfHHN+mw/fR+aPUGyQBJXjLHdD+mhXkCGeOCIBOASV4VkJqU/Ikt//EoUcfHj1pIa3A0tgz3L+CBeaYutod3HuIzdnG5ydckdBlTJve0pbepq5TpDPgYBwC91P1RrauiurteCOzZpBbeBizkLg=,iv:2l9LcdPITZxB101bNAozg3yfpnLlEUSmh4pJCE+7oRI=,tag:WrIAuk0XKCoPgR3r/yRgDA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
