#ENC[AES256_GCM,data:9F2IBCMwUm6vwqbQr3zJ1JHJijyYxROuUfkHYltKC5ElD4CnPJOCQsB8Rqi0IPNb2MpFKEeBXSEwEq4ElxJg,iv:Ex+QJGOJNr9vyuZ+RYslNkGvIFCtUEdM/O0LOVf7SFY=,tag:4DabYR6DK2OU5e6j2SY5Dg==,type:comment]
#ENC[AES256_GCM,data:tWXd1AdkEki14myZVXeUkVFqwZFmFzVUidgUaAIaDeE2GDeaXTGvqQlnYxQAlbFUZ0NMkaSpbOX5VypLYLg=,iv:zSmie6S9UoBXhjwc5zh4SnnDf4tMkvwWaEQ04Z9gBxY=,tag:9l6KQaWH20yJtR4v7p9ZwQ==,type:comment]
#ENC[AES256_GCM,data:7DiQiCU3teEiphzsIc64jaI+6CndRe3WOCMfOt8ItmVej+AlEr4RjA==,iv:hEYiFN/u0h6Be/rG9+QlBPu3KodPR7MGYeTAo7Kypu4=,tag:rta1utxukYfOxv1DS6buZA==,type:comment]
auth:
    rootPassword: ENC[AES256_GCM,data:DFfR0iaPpeAvXV/jh6e2pFBN+3t9NvlHaUAR3FAj3Iap+DQCec//gGYSvZfHu+6Q,iv:S2u/lIl2qp3WCk9Q/zoTmt81MIAVM+5jjQBzVrJituo=,tag:RvIUAMht9o5RQ/ZgI2w3yg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12t2lrvjt7r8k7sx2ef0q5wc9xj8kk3upxzr0kx3mqgya557z0uxsvna00u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcUk3RDhKb3B0VWwxRDU5
            TnpmU1BNQkprSzRvaEVIZ3NFSjNtUy9FdVVjCitMOEQrUmpZRWxHSHFJYzlhTWEy
            b1FieE5tSkw1bUlKTWt5MnBoYjFPbGMKLS0tIDF5dEpkZEh0QnVmSlBDSGNoQ2Nw
            cTVJdkNXMUtWazNJOXRwRWUraXFGdWcK8uLi6Jc1zMEiVChYLb+SVlF7WDuqjUcY
            0LYmpLYv1RemGzsmoGeW/N1lgbngG6tS8ehona0cme7Zy0WeamZ3cA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T23:56:47Z"
    mac: ENC[AES256_GCM,data:72qyBf5Qmas/ejodlz9d+RKn8kXyEHstjzDufdT4iAtvt7mQ2f+x0danWaGQ5OW8GhYjeAYWToR2TANe04fRt9PfYOtGrZbMwji9eiw6bgjUsePWeIkg4hq9iDFQkUi8ID0fbbyqDhgupq993IXTJ9e+xBFNGb58IPn8E/Xkjqs=,iv:galffCnY5/alkE/DYTNjcGxPOgJ7KPN+KYMFsf9oNWw=,tag:pXD36inSNQCd+Gu5PnxiLA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
